### ISSUE TITLE
Changelog tables in ABI

### ISSUE THREAD

**Issue by fpetrogalli** [ARM-software/software-standards#16]
I think we should convert the tables that track the changes in the ABI specifications in sections + paragraphs. At the moment, we see changes even in the rows describing the previous versions just because we need to reformat the table. I think this could be error prone (changes could be missed).

As an example of what I mean for "reformatting", see this PR:

https://github.com/ARM-software/software-standards/pull/15/files#diff-b590b56110000b706ad06b2250159441

**Comment by stuij** [comment]
This is a potential issue with any table. I personally think the table layout for the change log is quite nice in that it gives a nice clear view of the changes, and I'm not sure if the effort is worth the outcome.

**Comment by fpetrogalli** [comment]
> This is a potential issue with any table. 

Yes, but the other tables will rarely change. The changelog table will change every time we do a release of a document after changing it.

**Comment by stuij** [comment]
The main reason we see so many tables change in for this release is because the tables needed classes and therefore whole-table readjustments. In rare occasions I widened some columns so it's easier to add info. But in general the column width should stay static, either for changelog tables or other tables. Any changes to individual rows will of course only affect those rows, and for changelog tables this should only be new release info. And if it's just the table widening, and there are no other changes around the table, most diffing tools, including the github one will show incremental changes in a deeper color, which should make it clear that we're not accidentally changing things we don't want.

**Comment by fpetrogalli** [comment]
@stuij , I think you gave enough arguments to leave things the way they are. Closing this. Thank you.
